#!/bin/bash

# Run this file with "qsub -q <queue_name> -l select=<node_number>:ncpus=208 <this-script>.qsub"

#PBS -l walltime=00:59:00
#PBS -A e2sar-daos
#PBS -l filesystems=home:flare:daos_user_fs
#PBS -j oe

# Load DAOS module
module use /soft/modulefiles/ || { echo "Failed to use modulefiles"; exit 1; }
module load daos || { echo "Failed to load DAOS module"; exit 1; }

# Variables
NITER=${NITER:-10}   # pass via: qsub -v NITER=<n>
POOL_NAME=e2sar
NNODES=`wc -l < $PBS_NODEFILE` # Number of nodes
HOSTNAMES=$(cat $PBS_NODEFILE | tr '\n' ',')
echo "Nodes (${NNODES}): ${HOSTNAMES}"

START_TIME=$SECONDS

# Verify pool exists
daos pool list | grep -q -- "$POOL_NAME" || { echo "No pool: $POOL_NAME"; exit 1; }


# Compute node default path is $HOME
WKDIR=$HOME/iobench/pdsw26_daos-bench/scripts/aurora/ior   # <=== Change dir as needed
cd "${WKDIR}"


# skip-1 breadth scan. Bind 48 cores
CPU_BINDING_SKIP1="list:4:6:56:58:9:11:61:63:12:14:64:66:17:19:69:71:20:22:72:74:25:27:77:79:28:30:80:82:33:35:85:87:36:38:88:90:41:43:93:95:44:46:96:98:49:51:100:102"
export ZE_FLAT_DEVICE_HIERARCHY=COMPOSITE
export AFFINITY_ORDERING=compact

# Add ior into path
export PATH=$PATH:$HOME/ior/install/bin

echo "Running IOR write test"
# IOR parameters
# -i: Repeat the test this many times
# -o: the absolute path in the DFS container. Imagine txhe DFS root is /.
# --dfs.destroy: destroy the DAOS container after the test
# -b: ior block size, contiguous bytes to write per task
# -t: ior transfer size, size of transfer in bytes
# -s: number of segments. Not applied here.

CONTAINER_NAME="${USER}-ior_n${NNODES}"

create_container() {
    if daos cont query "$POOL_NAME" "$CONTAINER_NAME" >/dev/null 2>&1; then
        echo "Container $CONTAINER_NAME already exists, destroying it..."
        daos container destroy "$POOL_NAME" "$CONTAINER_NAME" || { echo "Failed to destroy container $CONTAINER_NAME"; exit 1; }
    fi
    daos container create --type=POSIX "$POOL_NAME" "$CONTAINER_NAME" --properties=rd_fac:0 \
        || { echo "Failed to create container $CONTAINER_NAME"; exit 1; }
    echo "Container $CONTAINER_NAME created."
    daos container get-prop "$POOL_NAME" "$CONTAINER_NAME"
}

destroy_container() {
    daos cont destroy "$POOL_NAME" "$CONTAINER_NAME" || echo "Failed to destroy container $CONTAINER_NAME"
}


# IOR smoke test
create_container
LD_PRELOAD=/usr/lib64/libpil4dfs.so mpiexec -np ${NRANKS} -ppn ${RANKS_PER_NODE} --cpu-bind ${CPU_BINDING_SKIP1}  \
                                            --no-vni -genvall -- \
                                            ior -a DFS -w -r \
                                            --dfs.pool $POOL_NAME --dfs.cont $CONTAINER_NAME --dfs.chunk_size=2m \
                                            -o /ior-smoke \
                                            -b 64M -t 16M
destroy_container


# different transfer sizes.
IOR_TX_SIZES=("2M" "16M")
NSEGMENTS=32

RESULTS_DIR="../../../results/aurora/ior/ior-rw"
mkdir -p $RESULTS_DIR


for RANKS_PER_NODE in 8 16 32 48; do
    NRANKS=$(( NNODES * RANKS_PER_NODE ))
    for tx_size in "${IOR_TX_SIZES[@]}"; do
        echo -e "\nRunning IOR read-write with transfer size: $tx_size, RANKS_PER_NODE: ${RANKS_PER_NODE}, total ranks: $NRANKS"
        create_container
        mpiexec -np ${NRANKS} -ppn ${RANKS_PER_NODE} --cpu-bind ${CPU_BINDING_SKIP1}  \
                                                    --no-vni -genvall -- \
                                                    ior -a DFS -w -r \
                                                    --dfs.pool $POOL_NAME --dfs.cont $CONTAINER_NAME --dfs.chunk_size=2m \
                                                    -o /ior-rw-tx_${tx_size}-ppn_${RANKS_PER_NODE} \
                                                    -s ${NSEGMENTS} -b 128M -t ${tx_size} -i ${NITER} \
                                                    -O summaryFile=${RESULTS_DIR}/ior_rw_n-${NNODES}_ppn-${RANKS_PER_NODE}_tx-${tx_size}_$(date +%s).csv -O summaryFormat=CSV
        sleep 5
        destroy_container
    done
done


ELAPSED_TIME=$((SECONDS - START_TIME))
echo "Completed script in $ELAPSED_TIME seconds"
